# Generated by Django 5.2.5 on 2026-03-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preprocessing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preprocessingtype",
            name="code_reference",
        ),
    ]
