# Generated by Django 5.2.5 on 2025-10-24 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadData', '0005_dataset_created_at_dataset_target_column'),
        ('mlstudio', '0002_commonparameter_remove_modelparameter_is_common'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_states', to='loadData.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlstudio.mlmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dataset', 'user')},
            },
        ),
    ]
