# Generated by Django 5.2.5 on 2025-10-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlstudio', '0003_datasetmodelstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodelstate',
            name='default_parameters',
            field=models.JSONField(default=dict),
        ),
    ]
