# Generated by Django 5.2.5 on 2025-10-25 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadData', '0005_dataset_created_at_dataset_target_column'),
        ('mlstudio', '0004_datasetmodelstate_default_parameters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_parameters', models.JSONField(default=dict)),
                ('model_parameters', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='loadData.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlstudio.mlmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
