# Generated by Django 5.2.5 on 2025-10-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlstudio', '0005_mlrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonparameter',
            name='data_type',
            field=models.CharField(choices=[('str', 'Tekst'), ('int', 'Liczba całkowita'), ('float', 'Liczba zmiennoprzecinkowa'), ('bool', 'Wartość logiczna (True/False)')], default='float', max_length=10),
        ),
        migrations.AddField(
            model_name='modelparameter',
            name='data_type',
            field=models.CharField(choices=[('str', 'Tekst'), ('int', 'Liczba całkowita'), ('float', 'Liczba zmiennoprzecinkowa'), ('bool', 'Wartość logiczna (True/False)')], default='str', max_length=10),
        ),
    ]
