# Generated by Django 5.2.5 on 2025-11-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlstudio', '0006_commonparameter_data_type_modelparameter_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonparameter',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='modelparameter',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='commonparameter',
            name='data_type',
            field=models.CharField(choices=[('str', 'str'), ('int', 'int'), ('float', 'float'), ('bool', 'bool')], default='float', max_length=10),
        ),
        migrations.AlterField(
            model_name='modelparameter',
            name='data_type',
            field=models.CharField(choices=[('str', 'str'), ('int', 'int'), ('float', 'float'), ('bool', 'bool')], default='str', max_length=10),
        ),
    ]
