# Generated by Django 5.2.5 on 2025-11-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlstudio', '0007_commonparameter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('REGRESSION', 'Regresja'), ('CLASSIFICATION', 'Klasyfikacja'), ('CLUSTERING', 'Klasteryzacja'), ('DIM_REDUCTION', 'Redukcja Wymiarowości')], default='CLASSIFICATION', max_length=20),
        ),
    ]
