# Generated by Django 5.2.5 on 2026-03-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelparameterdef",
            name="options",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
